hunt: driver.cpp event.cpp event.h bats.cpp bats.h gold.cpp gold.h pit.cpp pit.h wumpus.cpp wumpus.h room.h room.cpp game.h game.cpp
	g++ driver.cpp event.cpp bats.cpp gold.cpp pit.cpp wumpus.cpp room.cpp game.cpp -g -o hunt
